### ISSUE TITLE
the npm version @1.4.0 does not include /dist folder 

### ISSUE THREAD

**Issue by ghost** [thgreasi/localForage-cordovaSQLiteDriver#12]
Hi,
Package.json is pointing to `dist/localforage-cordovasqlitedriver.js` file but this one does not exist.
It sounds like the build did not run correctly and did not generate the `/dist` folder.

**Comment by thgreasi** [comment]
Ooooops! I'm on it.

**Comment by thgreasi** [comment]
> If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file.

Totally forgot about that... I usually include the dist folder in the repo as well, so this was never a problem so far. What's your opinion about that? Would including the dist folder to the repo add any value for you?

**Comment by thgreasi** [comment]
Just pushed v1.4.1 ! Thanks or reporting!
