### ISSUE TITLE
Use with Ionic 2

### ISSUE THREAD

**Issue by dimnls** [thgreasi/localForage-cordovaSQLiteDriver#13]
Hello there, I am having issues implementing the sqlite driver for localforage with Ionic 2.
I have localforage working correctly but I want to make sure it uses SQLite to avoid the space limitation.

The driver is not being detected correctly. Could you please provide some guidance?
Thanks!

**Comment by thgreasi** [comment]
I will try this out during the coming week. What does localforage.driver()
return?

What do you mean by:

> The driver is not being detected correctly.

Are you including the Cordova sqlite plugin? For comparison you might want
to take a look at the example ionic1 project referenced in README.

> ## 
> 
> _Thodoris Greasidis_

**Comment by thgreasi** [comment]
Καλημέρα.
I just added a [link in README pointing to a sample Ionic 2 project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonic2App).
I don't really like the way that I LocalForage exports & Typescript are dealing with each other and I hope that it will change in the future. Please note that I'm not a Typescript guru and any comments or PRs for the sample project are more than welcome.
