### ISSUE TITLE
Can't install from ionic start

### ISSUE THREAD

**Issue by azakusilo** [thgreasi/localForage-cordovaSQLiteDriver#18]
I try ionic start --v2 command on windows 8, but get this:

1081 silly install printInstalled
1082 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\Чубзик\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.git C:\Users\Чубзик\AppData\Roaming\npm-cache_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692
1082 verbose stack Cloning into bare repository 'C:\Users\Чубзик\AppData\Roaming\npm-cache_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692'...
1082 verbose stack Host key verification failed.
1082 verbose stack fatal: Could not read from remote repository.
1082 verbose stack
1082 verbose stack Please make sure you have the correct access rights
1082 verbose stack and the repository exists.
1082 verbose stack
1082 verbose stack     at ChildProcess.exithandler (child_process.js:214:12)
1082 verbose stack     at emitTwo (events.js:88:13)
1082 verbose stack     at ChildProcess.emit (events.js:173:7)
1082 verbose stack     at maybeClose (internal/child_process.js:819:16)
1082 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)

How to fix this?

**Comment by thgreasi** [comment]
The repository that you are referencing is a fork of this.
I think that that's an ionic issue. Most probably there is an issue with permissions.
Try adding a sudo in front.

**Comment by thgreasi** [comment]
Ref driftyco/ionic#8635

**Comment by mlynch** [comment]
Might also be related to this since we reference a github project. I'm going to move that over to using this repo now that there are typings, thanks @thgreasi!

https://github.com/driftyco/ionic-storage/issues/12

**Comment by thgreasi** [comment]
Great news :) I will drink a beer on that.

**Comment by azakusilo** [comment]
I don't have sudo command because I use windows 8. 

## I added the SSH public key to my GitHub account and the message:

## Host key verification failed.

Gone!

## But the message:

1089 verbose stack fatal: Could not read from remote repository.
1089 verbose stack
1089 verbose stack Please make sure you have the correct access rights
1089 verbose stack and the repository exists.
1089 verbose stack
1089 verbose stack     at ChildProcess.exithandler (child_process.js:214:12)
1089 verbose stack     at emitTwo (events.js:88:13)
1089 verbose stack     at ChildProcess.emit (events.js:173:7)
1089 verbose stack     at maybeClose (internal/child_process.js:819:16)

## 1089 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)

Is still here. May be anyone have any ideas?

**Comment by thgreasi** [comment]
[offtopic] @mlynch I'm using the `export =` syntax, just like localForage and PouchDB do (since these are UMD modules, not es6) but I saw that you were using the `export default`. Interestingly enough we have the exact same discussion in localForage/localForage#608 , so I would be very interested on your opinion about this.

**Comment by azakusilo** [comment]
In my case I had soled this than installed https://desktop.github.com/ (GitHub Application). And I open in it GitShell (right click on Tutorial). 
And OMG this works!
