### ISSUE TITLE
Uncaught (in promise) TypeError: undefined is not a function     at resolve (native)

### ISSUE THREAD

**Issue by chrisbarry** [thgreasi/localForage-cordovaSQLiteDriver#2]
I've included your code in my project, and I am getting the following error in the console:

Uncaught (in promise) TypeError: undefined is not a function     at resolve (native)

I was wondering if you had any idea about this? Does this code rely on requirejs or something like that?

**Comment by thgreasi** [comment]
We only rely on the existence of Promises (like localforage itself) and LocalForage.
In what order did you include your scripts?
Any chance you can find the line the exception was thrown?

**Comment by thgreasi** [comment]
You might want to take a look at the [Exaple Ionic project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) found in README.

**Comment by chrisbarry** [comment]
Ah, I've moved some of the scripts into an angular service as I was having a little trouble with things loading.

I'll follow the order as in the example (with inline script calls) and see if that sorts it out.

The load order will be:

Ionic
Cordova
localforage
localforage-cordovasqlitedriver

Inline defineDriver / setDriver 

Anything else

**Comment by thgreasi** [comment]
Can you find [`io.litehelpers.cordova.sqlite` in your `cordovaPlugins` section of `package.json`](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/blob/master/package.json)?
(Did you run `cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git`?)

Take a look at the [index.html of my sample app](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/blob/master/www/index.html).

**Comment by thgreasi** [comment]
Any progress/feedback on this?

**Comment by chrisbarry** [comment]
Yes, I loaded only the core js files:

```
<script src="lib/ionic/js/ionic.bundle.js"></script>
<script src="cordova.js"></script>
<script src="lib/localforage/dist/localforage.js"></script>
<script src="lib/localForage-cordovaSQLiteDriver/src/localforage-cordovasqlitedriver.js"></script>

<script type="text/javascript">
    var databaseLoaded = localforage.defineDriver(window.cordovaSQLiteDriver).then(function () {
            return localforage.setDriver([
                window.cordovaSQLiteDriver._driver,
                localforage.INDEXEDDB,
                localforage.WEBSQL,
                localforage.LOCALSTORAGE
            ]);
        });
</script>
```

And then all the other JS files.

I then wrapped any quick firing database calls in

```
databaseLoaded.then(function(){
    //DB code
});
```

This made sure that all db calls went to the native db. Previously some db calls ended up in localstorage or websql vis the browser.

**Comment by thgreasi** [comment]
Clad to hear that it worked for you :+1:

**Comment by sean-hill** [comment]
@thgreasi I am also having this issue, and have my code late out as @chrisbarry has described. In fact, I'm not calling any of the functions yet, just including the files in my `index.html` file. 

![screen shot 2016-01-07 at 3 31 44 pm](https://cloud.githubusercontent.com/assets/1205866/12184658/da957d4a-b553-11e5-9c2a-51d4ed4b01ce.png)

**Comment by thgreasi** [comment]
A full stacktrace would be really helpful. I would also be glad if you
could include some parts of your html and js code.

**Comment by thgreasi** [comment]
Have you installed the Cordova sqlite plugin? Also, did you include Cordova
and localforage before this plugin?

**Comment by sean-hill** [comment]
Hey, I removed my comment because of an error on my side :)

**Comment by thgreasi** [comment]
Happy you could fix this!

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer

**Comment by vegetablesalad** [comment]
@chrisbarry How did you resolve this? I'm getting the same error in cordova/PhoneGap. I'm not using the SQLite plugin trying to get it running with LOCALSTORAGE.

**Comment by chrisbarry** [comment]
If you're not using the SQLite plugin, then you shouldn't be using this driver (this is to make localforage work with the native local db).

Please be warned, I ran into a huge problem with iOS, where the web database options can be cleared out at any time. If you need data to be persistent, then please do start using the SQLite plugin, and this driver will help you use the simple localforage API on top of it.

**Comment by razam217** [comment]
Hi, how can I make sure that only SQLite db should be used. When I check in the Android ADB Plugin, it shows me that I'm using indexedDB.

**Comment by thgreasi** [comment]
> You might want to take a look at the [Exaple Ionic project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) found in README.

Just call set driver with the desired driver as the only parameter (instead of an array).

``` js
localforage.defineDriver(window.cordovaSQLiteDriver).then(function () {
    return localforage.setDriver(window.cordovaSQLiteDriver._driver);
});
```

**Comment by razam217** [comment]
And how can I check what is used behind?

**Comment by razam217** [comment]
Instead of array when I passed only SQLiteDriver LocalForage is throwing me exception
"Driver not found."

**Comment by razam217** [comment]
```
window.localforage.defineDriver(window.cordovaSQLiteDriver).then(function() {
      return window.localforage.setDriver(window.cordovaSQLiteDriver._driver);
}).then(function() {
      // further code
});
```

I'm doing it this way...

**Comment by thgreasi** [comment]
You are probably missing some references/includes.

> You might want to take a look at the [Exaple Ionic project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) found in README.

**Comment by razam217** [comment]
I've checked each and everything in Test App. And doing the same way.

**Comment by thgreasi** [comment]
Have you tried to clone and run the Example project?

**Comment by razam217** [comment]
Sorry, my app configuration due to gulp was a bit different, and was adding this library before cordova, so now it is fixed... Thanks a lot for quick support.

**Comment by razam217** [comment]
Hi, I'm receiving Disk I/O error. While setting and getting values, but sometime not always. I don't know why. Can you please help me out of this?

**Comment by thgreasi** [comment]
Can you share a stacktrace of the error?
How much data have you already stored before getting this error?
What device, OS and versions is this happening?

**Comment by razam217** [comment]
**Devices:** Android 5.0 & IOS 9.3.2
**JSON:** https://www.dropbox.com/home/ZIGRON?preview=JSON.txt
**Stack Trace:** Disk I/O error

**Comment by razam217** [comment]
Amount of data I've already stored will be almost 10-15 times of this json...

**Comment by thgreasi** [comment]
That wasn't a sharable dropbox link.

**Comment by razam217** [comment]
Did you find any problem, or reason behind this issue?

**Comment by thgreasi** [comment]
Unfortunately, I wasn't able to reproduce. We need further confirmations
and info about the occasions that this occurs. Also I think you should
better open a new issue to track this down since I don't think that it's
related to this one.

> ## 
> 
> _Thodoris Greasidis_

**Comment by rodrigorellana** [comment]
i'm using vscode in my angular proyect, same error then simply stop ng serve close vscode (ensure from process) then reopen vscode and try again, it worked for me
