### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by finitha** [thgreasi/localForage-cordovaSQLiteDriver#20]
Hi, I have installed correctly the plugin in my Ionic 1 App.
But when I try on an android device, I have this error : 
`TypeError: Cannot read property '_driver' of undefined` in the AlertBox.

It works on IOS Emulator and return : 
`cordovaSQLiteDriver`
Do you have any solution ?

Thanks in advance

**Comment by thgreasi** [comment]
Have you checked the [ionic 1 sample project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) found in README?

**Comment by thgreasi** [comment]
Most probably, the sqlite driver was not installed properly and needs a re-installation.

**Comment by finitha** [comment]
Yep I have checked the sample projet.

I will try a re-installation  of the sqlite driver....

Edit, I ran : 
`bower with: bower install --save localforage localForage-cordovaSQLiteDriver`

but still the same problem.. Do you need other information ?

Thanks in advance

**Comment by thgreasi** [comment]
Please also try reinstalling the cordova sqlite plugin `cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git`.

**Comment by thgreasi** [comment]
I just cloned the ionic sample project:
* `cd` in the folder
* `bower i`
* `ionic platform add android`
* `cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git`
* `ionic emulate android`

and it worked in the emulator.

**Comment by finitha** [comment]
Hi,
I tried to re-install everything in my app and I had always the same result.
So, I opened bower.json of your sample and added : 
`"localforage": "^1.4.0",
    "localForage-cordovaSQLiteDriver": "^1.3.0"`
in my project and ran bower install.
Now it works on Android and IOS
So maybe the problem was with the new version of localforage or sqlitedriver ?
Thanks for your help :)

**Comment by thgreasi** [comment]
Oh, you have a point.
Using the latest versions of localForage & localForage-cordovaSQLiteDriver (v1.5 & v1.6 respectively), I had to change the path to point to the `dist` folder:
```html
<script src="lib/localForage-cordovaSQLiteDriver/dist/localforage-cordovasqlitedriver.js"></script>
```
Updating README and sample app now.
