### ISSUE TITLE
I'm unable to get this working

### ISSUE THREAD

**Issue by john-doherty** [thgreasi/localForage-cordovaSQLiteDriver#22]
I get a console log of `asyncStorage` when using the following code:

```
localforage.defineDriver(window.cordovaSQLiteDriver).then(function() {
    return localforage.setDriver([
        // Try setting cordovaSQLiteDriver if available,
        window.cordovaSQLiteDriver._driver,
        // otherwise use one of the default localforage drivers as a fallback.
        // This should allow you to transparently do your tests in a browser
        localforage.INDEXEDDB,
        localforage.WEBSQL,
        localforage.LOCALSTORAGE
    ]);
})
.then(function() {

    localforage.config({
        name: 'db',
        version: 1.0,
        size: 104857600, // 100mb
        storeName: 'mydata'
    });

    console.log('DB Driver = ' + localforage.driver());
});
```

According to your docs, it should be `cordovaSQLiteDriver`... Any idea's what I'm doing wrong?

**Comment by thgreasi** [comment]
What version of the libraries are you using?
Please check the value of `window.cordovaSQLiteDriver`.
Also check out the example repos found in README to ensure that the Cordova plugin is correctly  configured.

**Comment by john-doherty** [comment]
> What version of the libraries are you using?

localForage 1.5.0
localForage-cordovaSQLiteDriver v1.6.0
cordova 7.0.1
cordova-sqlite-storage 2.0.4

> Please check the value of window.cordovaSQLiteDriver.

`JSON.stringify(window.cordovaSQLiteDriver)` returns `{"_driver": "cordovaSQLiteDriver"}`

Is calling `localforage.config` after `localforage.setDriver` _(as in my example above)_ causing a problem?

**Comment by john-doherty** [comment]
I figured it out. I was missing the [SQLitePlugin.js](https://raw.githubusercontent.com/litehelpers/Cordova-sqlite-storage/storage-master/www/SQLitePlugin.js) script from the [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) plugin. I wrongly assumed it would add it's own dependency scripts.

Thanks for your help :)

**Comment by john-doherty** [comment]
@thgreasi I found the problem, it's an issue with [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage/issues/721). If you build your cordova app using `cordova prepare --browserify` _(bundles all dependant scripts into cordova.js)_ window.sqlitePlugin returns `undefined`. Which causes your lib to fail.

**Comment by thgreasi** [comment]
Do you have any clue what's the proper way to get a reference of that object in that case?

**Comment by john-doherty** [comment]
No. I've removed the `--browserify` switch for now and raised a ticket on the other repo. It's not a _localForage-cordovaSQLiteDriver_ issue, so I'd avoid any workarounds and wait for a fix.... Just wanted to keep you in the loop :)

**Comment by thgreasi** [comment]
Thanks for sharing your feedback in here :+1:

**Comment by john-doherty** [comment]
Hi @thgreasi, despite the issue above - I'm still not able to get this working. I'm not sure I understand the `localForage` lifecycle correctly... I've posted a [SO question](https://stackoverflow.com/questions/47005022/what-is-the-correct-way-to-use-localforage-with-cordova)

**Comment by thgreasi** [comment]
Cross posting the [SO answer](https://stackoverflow.com/a/47010299/1206668) here as well:
> So, first of all, `createInstance()` returns a totally new & unrelated instance of localforage and reinitializes from scratch. So the new instance will try to settle on which driver to use, using the default driver preference order (IndexedDB, WebSQL, LocalStorage). The only thing that all localforage instances share is the available/defined drivers.
So you can do something like this:
```js
localforage.defineDriver(window.cordovaSQLiteDriver).then(function() {
    window.appStorage = localforage.createInstance({
        version: 1.0,
        size: 52428800, // 50mb
        name: 'my-app-name',
        storeName: 'setup',
        driver: [
            window.cordovaSQLiteDriver._driver, // <-- prefer cordovaSQLiteDriver
            localforage.INDEXEDDB,
            localforage.WEBSQL,
            localforage.LOCALSTORAGE
        ]
        // OR instead of passing the `driver` option,
        // you can call `window.appStorage.setDriver()`
        // right after `createInstance()`
    });

    if (window.appStorage.driver() !== window.cordovaSQLiteDriver._driver) {
        console.warn('Not using cordovaSQLiteDriver before setItem.');
    }

    return appStorage.setItem('message', 'It worked!');
})
.then(function() {
    return appStorage.getItem('message');
})
.then(function(message){
    console.log(message);
    if (window.appStorage.driver() !== window.cordovaSQLiteDriver._driver) {
        console.warn('Not using cordovaSQLiteDriver after setItem.');
    }
});
```

**Comment by john-doherty** [comment]
Thank you @thgreasi. It was my lack of understanding that was causing the problem, this did indeed resolve my issue.

It might be wise to update the docs to give an example of creating an instance and setting the driver etc as I could not get the current example to work.

Thanks again!
