### ISSUE TITLE
How do you confirm localForage is writing to cordova SQLite?

### ISSUE THREAD

**Issue by john-doherty** [thgreasi/localForage-cordovaSQLiteDriver#23]
If I execute `localforage.driver()` in the console it returns **cordovaSQLiteDriver**, however I can see the data is actually been written to IndexedDB... Do you have a way of viewing or confirming data is actually written to the cordova SQL Lite db?

**Comment by thgreasi** [comment]
In that case, if you run `.driver()` on your localforage instance, after setting your items, it should not return `cordovaSQLiteDriver`.
First of all you should be able to locate a DB file on the device's filesystem (take a look at the [cordova's plugin docs](https://github.com/litehelpers/Cordova-sqlite-storage)).
Other than that, you should be able to use the [tools](https://stackoverflow.com/questions/29138442/browse-sqlite-database-from-android-studio) that are available for your IDE to insect the generated DB file & content.

**Comment by john-doherty** [comment]
Hi @thgreasi, I'm trying to inspect the data on an iOS device... 

I resorted to opening Safari on the mac, connecting to the app on the device and executing the following from the Safari console:

```js
db = window.sqlitePlugin.openDatabase({name: "database-name"});
db.transaction(function(tx) {
    tx.executeSql('SELECT * FROM tableName', [], function(tx,results) {
        for (var i=0; i < results.rows.length; i++){
            row = results.rows.item(i);
            console.log("row is " + JSON.stringify(row));
        }
    });
});
```

**Comment by thgreasi** [comment]
Thanks for reporting back in here with so many details 👍

**Comment by sithwarrior** [comment]
@john-doherty Sorry to bother since this is an old issue, but how did you mange to fix it?

I've installed the plugins, i get the **cordovaSQLiteDriver** when i run `localforage.driver()`
I can run the self test etc. but data still seems to be stored/retrieved from indexedDB.

**Comment by john-doherty** [comment]
Hi @sithwarrior, if I remember correctly my issue was around timing and my lack of understanding around how instances work. I posted [a related question on SO](https://stackoverflow.com/questions/47005022/what-is-the-correct-way-to-use-localforage-with-cordova) at the time and @thgreasi kindly answered. His response might help you.

**Comment by sithwarrior** [comment]
Hi @john-doherty thanks. that helped me in the right direction.
