### ISSUE TITLE
Defining the cordovaSQLiteDriver driver in sync

### ISSUE THREAD

**Issue by sithwarrior** [thgreasi/localForage-cordovaSQLiteDriver#25]
We want to migrate our Ionic 1 app, which uses localforage, to the cordovaSQLiteDriver.

When changing to the cordovaSQLiteDriver, we get some setup code, that looks similar to this:

```javascript 
storeNames = [
            'images',
            'authentication',
            'notifications'
];
localforage.defineDriver(window.cordovaSQLiteDriver).then(() => {
                this.storeNames.forEach((storeName) => {
                    let newStore = this.$localForage.createInstance({
                        name: storeName,
                        driver: [
                            window.cordovaSQLiteDriver._driver, // <-- prefer cordovaSQLiteDriver
                            localforage.INDEXEDDB,
                            localforage.WEBSQL,
                            localforage.LOCALSTORAGE
                        ]
                    });
    
                    
                })
            })
```

However, since the localforage.defineDriver, makes this code async, the controllers wanting to obtain for example the notifications store, fails because it does not exist yet ie:

```javascript 
this.notificationStorage = $localForage.instance('notifications') // fails no instance with this name exists
```

I've read a lot of the documentation, and it seems that defineDriver will run sync, if the _support property on the driver isnt a function. but reading the source, _support on the cordovaSQLiteDriver seems to be reponsible for creating the database etc.

Any help, solutions or workarounds, would be very much appreciated

**Comment by thgreasi** [comment]
If you are migrating data, then this sounds like it deserves a spinner anyway. The rest of your app will probably have to wait for some setItem calls to complete before trying to fetch anything, so your migration code should wait for all the instances to become available and the rest of the app should wait for the migrations to complete.

I would create a services with two methods returning a promise, one to indicate that the db instances got created and one to indicate that the migrations completed.

I will give this some extra thought during the weekend.

**Comment by thgreasi** [comment]
Ionic storage uses this approach as well if you check its constructor code https://github.com/ionic-team/ionic-storage/blob/master/src/storage.ts and provide their own .ready() method, as described in my previous comment.

**Comment by sithwarrior** [comment]
@thgreasi Thank for great reponse. I moved stuff around, and made it work inspired by that solution.

However having an app, thats made of many components with seperate localForage instances, made it a little bit difficult, as many methods now have to depend on a promise, to ensure the instance is created, before accessing it.

It would be nice with a method like localforage.defineDriverSync, so one had the option of doing it synchronously.

**Comment by thgreasi** [comment]
As an alternative to keep your components independent from those async concerns, you could add a spinner to your app and have your router only load each component once the respective instances are ready. Taking it one step further, you could prepare all instances during all loading and assume their existence inside your components.
