### ISSUE TITLE
Ionic requirement

### ISSUE THREAD

**Issue by sido420** [thgreasi/localForage-cordovaSQLiteDriver#26]
I just wanted to make sure its really needed to use Ionic in order to use this driver. Cant I use this driver with any other framework?

ionic is listed under requirements section.

**Comment by thgreasi** [comment]
Ionic is not required at all.
I mentioned `Cordova/ionic` (with a `/` meaning `or`) since some people using ionic are not aware what cordova means.
You really just need having cordova and the respective driver installed and properly include them to your project.

**Comment by sido420** [comment]
And some people (like me) using Cordova don't know how ionic works :)

I was under the impression that ionic runs on top of Cordova. Also, ionic seems to have its own LF based storage.

**Comment by sido420** [comment]
Thanks.
