### ISSUE TITLE
Err: transaction expected a function

### ISSUE THREAD

**Issue by sido420** [thgreasi/localForage-cordovaSQLiteDriver#27]
I've already looked at SO answer on how to initialize etc.

I have a use case where I create an instance (App.AccountsDB) with default set of drivers and later change the instance's driver to SQLite but getting the following err on setItem().

Error message in console:
```
Error: transaction expected a function
    at newSQLError (SQLitePlugin.js:26)
    at new SQLitePluginTransaction (SQLitePlugin.js:310)
    at SQLitePlugin.transaction (SQLitePlugin.js:118)
    at N (localforage.js:792)
    at localforage.js:1024
(anonymous) @ storage.js:94
(anonymous) @ localforage.js:442
Promise.then (async)
a @ localforage.js:439
setItem @ localforage.js:1066
(anonymous) @ storage.js:93
(anonymous) @ storage.js:67
callbackFromNative @ cordova.js:294
processMessage @ cordova.js:1120
processMessages @ cordova.js:1143
Promise.then (async)
nextTick @ cordova.js:936
androidExec @ cordova.js:978
deleteDatabase @ SQLitePlugin.js:630
cleanupAndFinish @ SQLitePlugin.js:861
(anonymous) @ SQLitePlugin.js:842
callbackFromNative @ cordova.js:294
(anonymous) @ VM147:1
```

Here is the code snippet (with line 94):

```
            localforage.defineDriver(window.cordovaSQLiteDriver)
                .then(function () {
                    performEchoTest(null, function () { //sqlite plugin echo test here
                        if (App.AccountsDB && window.cordovaSQLiteDriver &&
                            window.cordovaSQLiteDriver._driver &&
                            App.AccountsDB.driver() !== window.cordovaSQLiteDriver._driver) {
                            
                            App.AccountsDB.setDriver(window.cordovaSQLiteDriver._driver);
                            App.AccountsDB.setItem('test', 'test', function (err) {
                                if (err) console.error(err);    // <-- storage.js:94
                                deferred.resolve();
                            });
                        } else {

                            deferred.resolve();
                        }
                    });//performEchoTest
                });//defineDriver
```

Also, I've already tried switching positions of defineDriver() and performEchoTest(). see echo test details at https://github.com/litehelpers/Cordova-sqlite-storage#self-test

SQLite related code is called after deviceReady event and echo test is OK.

NOTE: .driver() right after setDriver() call still returns old driver label ("asyncStorage" etc), which means setItem shouldn't fail. However, running .driver() in console (once everything has loaded) results in cordovaSQLiteDriver. Is setDriver() an async function?

**Comment by sido420** [comment]
LF version  "version": "1.7.1"

**Comment by sido420** [comment]
Please ignore the tests in if statement (its random test code).

**Comment by thgreasi** [comment]
Yes, both defineDriver and setDriver return a promise/are async. As you can see in the readme we are channing setDriver by returning its result.
Closing this for now but please reopen if this is still an issue for you.

**Comment by sido420** [comment]
Ok, I was looking at https://localforage.github.io/localForage/#settings-api-setdriver and it does not appear to be async from details there (unless I missed something).
