### ISSUE TITLE
db size limit

### ISSUE THREAD

**Issue by s-pic** [thgreasi/localForage-cordovaSQLiteDriver#28]
AFAIK SQLite database files do not have a size limit.
So am I seeing this right:
The db file could take as puch space as the applications sandbox is allowed to grow.

Or is some other size limitation to be considered?

**Comment by thgreasi** [comment]
Hi, I'm not aware of any size limitation.
I would suggest you to check out https://github.com/litehelpers/Cordova-sqlite-storage/ for further details on this, since that's the underlying implementation that this repo was built on top.
