### ISSUE TITLE
Error when using Phonegap Build

### ISSUE THREAD

**Issue by netzzeit** [thgreasi/localForage-cordovaSQLiteDriver#29]
Hey,

I would like to use this localForage-Driver with PhoneGap Build. I have the following lines in my config.xml:
    
`<plugin name="cordova-sqlite-evcore-extbuild-free" source="npm" />
  <plugin spec="https://github.com/thgreasi/localForage-cordovaSQLiteDriver.git" source="git" />`

Unfortunately PGB throws the following error:

Repository "https://github.com/thgreasi/localForage-cordovaSQLiteDriver.git" checked out to git ref "master" at "00ce8b3".
Failed to fetch plugin https://github.com/thgreasi/localForage-cordovaSQLiteDriver.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Cannot find plugin.xml for plugin "1527324989723". Please try adding it again.

The same error occurs when I use the NPM-version.

Is there any workaround for that? I would really appreciate any tips.

Thank you. :)

**Comment by thgreasi** [comment]
This isn't meant to be declared in your config.xml, only the Cordova plugin part should be there. As mentioned in [npm](https://www.npmjs.com/package/localforage-cordovasqlitedriver) and in README you should be able to install this with `npm i --save localforage localforage-cordovasqlitedriver`. Are you getting any error with this? Since ionic 1 is mostly plain Cordova, I would suggest you to check out the ionic 1 sample repo found in the README.

**Comment by netzzeit** [comment]
Hey thgreasi, 
thank you for your fast response. I don't know whether you are familiar with Phonegap Build. There is no option to use npm-commands to install plugins. Plugins can only be installed via the syntax above. But maybe it is not compatible with your driver-plugin.

Is is possible to install the cordova-sqlite-plugin the "Phonegap Build"-way (which is working) and add your custom driver as a regular javascript-file within my project? That could be a workaround... :)

**Comment by thgreasi** [comment]
It should be, since Cordova build will combine all Cordova plugins into a single cordova.js file but you should be able to reference other js resources normally, depending on your setup, just like ionic 1 did.

**Comment by netzzeit** [comment]
Great - that did the trick. Thank you very much and keep up the excellent work! :)
