### ISSUE TITLE
dropinstance() missing?

### ISSUE THREAD

**Issue by sido420** [thgreasi/localForage-cordovaSQLiteDriver#30]
Is dropInstance not implemented for this driver? Why?

**Comment by thgreasi** [comment]
Yea, that's true, I haven't updated this driver since the release of LF v1.6 (which added the `dropInstance()` method).
Will add this in my todo list.

**Comment by thgreasi** [comment]
@sido420 PR #36 should be addressing this. It would be great if you could give this a try on a realistic app and share your feedback.
