### ISSUE TITLE
Dates are not converted correctly with this Driver

### ISSUE THREAD

**Issue by gabn88** [thgreasi/localForage-cordovaSQLiteDriver#33]
Before I installed this driver and used indexeddb and websql, everything was working fine. But now dates don't seem to convert back to Date objects when retreived from the cordovaSQLite database. Instead they come back as strings, which is very annoying.

I'm using https://github.com/litehelpers/Cordova-sqlite-storage/ although I'm not sure if the actual SQLite implementation matters in this case.

**Comment by gabn88** [comment]
It turns out that indexeddb has native support for Date objects, which is why that works fine. Sqlite does not have support for Date objects, so they are serialized. Calling new Date(serializedDate) converts it back to the right Date object.

**Comment by thgreasi** [comment]
If this get's fixed in the websql driver of LF, this one will pick it up right away.
