### ISSUE TITLE
Question about the DB

### ISSUE THREAD

**Issue by sean-hill** [thgreasi/localForage-cordovaSQLiteDriver#4]
More a question than an issue, but I've done some digging and can't find the answer. I would like to see, either on my emulator or actual device the SQLite DB that was created. I just want to verify that the Driver is working and not just using local storage. `alert(localforage.driver());` does say `cordovaSQLiteDriver` but I just want to be completely sure there is a DB :smile:

**Comment by thgreasi** [comment]
Hmmmm, I don't know the answer for this. I would suggest you to take a look
at https://github.com/litehelpers/Cordova-sqlite-storage for more info.
I you find an answer for this, I would be glad if you could cross-post your
findings here.

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer
