### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Harper04** [thgreasi/localForage-cordovaSQLiteDriver#5]
Using:
import 'localforage-cordovasqlitedriver';

i get 
gulp-notify: [Compile Error] 'import' and 'export' may appear only with 'sourceType: module'

```
"babel-core": "^6.3.26",
"babel-preset-es2015": "^6.3.13",
"babelify": "^7.2.0",
```

with .babelrc
{
  "presets": ["es2015"]
}

**Comment by thgreasi** [comment]
Thanks for the heads up but this repo does not use babel or es6 at all.
That's probably what the error message wants to point, since the import is pointed at a normal es5 js file and not an es6 module.

**Comment by Harper04** [comment]
Tank you,
all this transpiler babel stuff is confusing if you are used to compiled languages.
Andy thoughts about how to include this without using a script Tag in Index.html?

**Comment by thgreasi** [comment]
What target module type do you have in your babel configuration?
Since this is an UMD module, you should be able to load it with other `require` method (requirejs/webpack). You might also be able to use SystemJS.
I might have to rewrite this to ES6 sometime this year...

**Comment by thgreasi** [comment]
Closing this for now.
If this is still an issue feel free to re-open in any case.
