### ISSUE TITLE
After initiation

### ISSUE THREAD

**Issue by sean-hill** [thgreasi/localForage-cordovaSQLiteDriver#9]
`localforage.driver()` is returning `webSQLStorage` for me not `cordovaSQLiteDriver`. I have the `cordova-sqlite-plugin` installed in my project. How can I debug this further?

![screen shot 2016-05-19 at 10 32 20 am](https://cloud.githubusercontent.com/assets/1205866/15403272/fd760570-1dac-11e6-97ed-f2f0f46c389b.png)

I had been using this plugin for months assuming that it was storing it in a SQL databse and not local storage. However, my users are complaining that their storage is being lost on their iOS devices. I asked each of them and they each had less than 100 MB left on their device of free space. I assume iOS is going through and wiping out my apps local storage. I assumed that SQL would not be wiped out, hence the reason I used this plugin instead of just `window.localStorage`.

**Comment by thgreasi** [comment]
What versions of the plugins are you using?
Can you try the [example ionic app](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) on iOS and report back your results?

**Comment by sean-hill** [comment]
I'm using the latest of everything now. Same results. I took a look at the `localforage` library's code:

```
var driverSupport = {};
// Check to see if IndexedDB is available and if it is the latest
// implementation; it's our preferred backend library. We use "_spec_test"
// as the name of the database because it's not the one we'll operate on,
// but it's useful to make sure its using the right spec.
// See: https://github.com/mozilla/localForage/issues/128
driverSupport[DriverType.INDEXEDDB] = isIndexedDBValid();

driverSupport[DriverType.WEBSQL] = isWebSQLValid();

driverSupport[DriverType.LOCALSTORAGE] = isLocalStorageValid();
```

It appears it doesn't even support `cordovaSQLiteDriver`. I'll take a look at the sample repo and report back the results.

**Comment by thgreasi** [comment]
> It appears it doesn't even support cordovaSQLiteDriver. I'll take a look at the sample repo and report back the results.

Of course. This is a custom driver plugin for localforage. By definition `cordovaSQLiteDriver` is not part of the localforage source code. 

To be honest, in the source code that you posted, I can't see where you import this driver (as shown in README):

``` js
<script src="lib/localForage-cordovaSQLiteDriver/src/localforage-cordovasqlitedriver.js"></script>
```

**Comment by sean-hill** [comment]
Just tested the sample Ionic app, and of course `localforage.driver()` returns `cordovaSQLiteDriver` 😄  Hmmm...

Cordova SQLite Storage - v1.4.1
Localforage - v1.4.2
Your driver - v1.3.0

My apologies, I copied your source and renamed it to a file called `sqlite.js`. Let me copy everything from the Ionic Test App, and try that. Thanks!

**Comment by thgreasi** [comment]
If you can suggest anything that would improve the docs, I would be happy to review and merge (if it's a PR).

**Comment by sean-hill** [comment]
The issue was with Ionic's `ionic-platform-web-client`. They required the `<script src="cordova.js"></script>` to be removed because `Cordova is bootstrapped by ionic-platform-web-client`. However this caused your driver `else if (!globalObject.cordova) {` to fire since `cordova.js` was not available, which ended up not loading the SQLite DB. Adding back in `<script src="cordova.js"></script>` fixed the issue.
